package com.clothings.springBoot.model;

public class Category {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.Id
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.Code
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.Name
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.Id
	 * @return  the value of category.Id
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.Id
	 * @param id  the value for category.Id
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.Code
	 * @return  the value of category.Code
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.Code
	 * @param code  the value for category.Code
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.Name
	 * @return  the value of category.Name
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.Name
	 * @param name  the value for category.Name
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}
}