package com.clothings.springBoot.model;

public class OrderDetail extends OrderDetailKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderdetail.Quantity
	 * @mbg.generated  Mon Nov 06 16:24:17 ICT 2023
	 */
	private Integer quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderdetail.UnitPrice
	 * @mbg.generated  Mon Nov 06 16:24:17 ICT 2023
	 */
	private Double unitprice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderdetail.Quantity
	 * @return  the value of orderdetail.Quantity
	 * @mbg.generated  Mon Nov 06 16:24:17 ICT 2023
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderdetail.Quantity
	 * @param quantity  the value for orderdetail.Quantity
	 * @mbg.generated  Mon Nov 06 16:24:17 ICT 2023
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderdetail.UnitPrice
	 * @return  the value of orderdetail.UnitPrice
	 * @mbg.generated  Mon Nov 06 16:24:17 ICT 2023
	 */
	public Double getUnitprice() {
		return unitprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderdetail.UnitPrice
	 * @param unitprice  the value for orderdetail.UnitPrice
	 * @mbg.generated  Mon Nov 06 16:24:17 ICT 2023
	 */
	public void setUnitprice(Double unitprice) {
		this.unitprice = unitprice;
	}
}