package com.clothings.springBoot.model;

public class OrderDetailKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderdetail.OrderId
	 * @mbg.generated  Mon Nov 06 16:24:17 ICT 2023
	 */
	private Integer orderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderdetail.ProductId
	 * @mbg.generated  Mon Nov 06 16:24:17 ICT 2023
	 */
	private Integer productid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderdetail.OrderId
	 * @return  the value of orderdetail.OrderId
	 * @mbg.generated  Mon Nov 06 16:24:17 ICT 2023
	 */
	public Integer getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderdetail.OrderId
	 * @param orderid  the value for orderdetail.OrderId
	 * @mbg.generated  Mon Nov 06 16:24:17 ICT 2023
	 */
	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderdetail.ProductId
	 * @return  the value of orderdetail.ProductId
	 * @mbg.generated  Mon Nov 06 16:24:17 ICT 2023
	 */
	public Integer getProductid() {
		return productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderdetail.ProductId
	 * @param productid  the value for orderdetail.ProductId
	 * @mbg.generated  Mon Nov 06 16:24:17 ICT 2023
	 */
	public void setProductid(Integer productid) {
		this.productid = productid;
	}
}