package com.clothings.springBoot.model;

import java.util.Date;

public class Product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.Id
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.CategoryId
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	private Integer categoryid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.Picture
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	private String picture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.Name
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.Code
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.costPrice
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	private Float costprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.unitPrice
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	private Float unitprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.Sold
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	private Integer sold;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.Sale
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	private Integer sale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.stockInDate
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	private Date stockindate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.Id
	 * @return  the value of product.Id
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.Id
	 * @param id  the value for product.Id
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.CategoryId
	 * @return  the value of product.CategoryId
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public Integer getCategoryid() {
		return categoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.CategoryId
	 * @param categoryid  the value for product.CategoryId
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public void setCategoryid(Integer categoryid) {
		this.categoryid = categoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.Picture
	 * @return  the value of product.Picture
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public String getPicture() {
		return picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.Picture
	 * @param picture  the value for product.Picture
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public void setPicture(String picture) {
		this.picture = picture == null ? null : picture.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.Name
	 * @return  the value of product.Name
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.Name
	 * @param name  the value for product.Name
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.Code
	 * @return  the value of product.Code
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.Code
	 * @param code  the value for product.Code
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.costPrice
	 * @return  the value of product.costPrice
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public Float getCostprice() {
		return costprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.costPrice
	 * @param costprice  the value for product.costPrice
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public void setCostprice(Float costprice) {
		this.costprice = costprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.unitPrice
	 * @return  the value of product.unitPrice
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public Float getUnitprice() {
		return unitprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.unitPrice
	 * @param unitprice  the value for product.unitPrice
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public void setUnitprice(Float unitprice) {
		this.unitprice = unitprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.Sold
	 * @return  the value of product.Sold
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public Integer getSold() {
		return sold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.Sold
	 * @param sold  the value for product.Sold
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public void setSold(Integer sold) {
		this.sold = sold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.Sale
	 * @return  the value of product.Sale
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public Integer getSale() {
		return sale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.Sale
	 * @param sale  the value for product.Sale
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public void setSale(Integer sale) {
		this.sale = sale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.stockInDate
	 * @return  the value of product.stockInDate
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public Date getStockindate() {
		return stockindate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.stockInDate
	 * @param stockindate  the value for product.stockInDate
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	public void setStockindate(Date stockindate) {
		this.stockindate = stockindate;
	}
}