package com.clothings.springBoot.mapper;

import com.clothings.springBoot.model.User;
import com.clothings.springBoot.model.UserExample;
import com.clothings.springBoot.model.UserKey;
import com.clothings.springBoot.model.UserWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	long countByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	int deleteByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	int insert(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	int insertSelective(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	List<User> selectByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") User row, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Oct 03 17:58:08 ICT 2023
	 */
	int updateByExample(@Param("row") User row, @Param("example") UserExample example);
}